variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$nextjs-ui/src/app'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
